codecov

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,19 +9,32 @@ jobs:
         run: |
           docker pull openturns/archlinux-module
           docker run -e MAKEFLAGS='-j2' -v `pwd`:/io openturns/archlinux-module /io/.ci_support/run_docker_linux.sh `id -u` `id -g`
-      - name: Upload
-        if: ${{ github.ref == 'refs/heads/master' }}
-        run: |
-          git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/openturns/openturns.github.io.git /tmp/io
-          mkdir -p /tmp/io/otsvm/master
-          cp -r html/* /tmp/io/otsvm/master
-          cd /tmp/io
-          touch .nojekyll
-          git config user.email "support@gh.com"
-          git config user.name "GitHub Actions"
-          git add -A .
-          git commit -a -m "GitHub Actions build ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}" || exit 0
-          git push --quiet origin master > /dev/null 2>&1
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          slug: jschueller/otsvm
+          #directory: ./html/coverage
+          #env_vars: OS,PYTHON
+          #fail_ci_if_error: true
+          file: ./html/coverage/coverage.info
+          #files: ./coverage1.xml,./coverage2.xml,!./cache
+          #flags: unittests
+          #name: codecov-umbrella
+          verbose: true
+      #- name: Upload
+        #if: ${{ github.ref == 'refs/heads/master' }}
+        #run: |
+          #git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/openturns/openturns.github.io.git /tmp/io
+          #mkdir -p /tmp/io/otsvm/master
+          #cp -r html/* /tmp/io/otsvm/master
+          #cd /tmp/io
+          #touch .nojekyll
+          #git config user.email "support@gh.com"
+          #git config user.name "GitHub Actions"
+          #git add -A .
+          #git commit -a -m "GitHub Actions build ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}" || exit 0
+          #git push --quiet origin master > /dev/null 2>&1
 
   mingw:
     runs-on: ubuntu-latest
